global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-service:8087']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'feedback-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['feedback-service:8084']

  # Add service discovery for dynamic scaling
  - job_name: 'eureka-discovery'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://discovery-service:8087/eureka

# Alerting rules
rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093' 