server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3307/user
    username: postgres
    password: 6531503042
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ofBra2CqJO2JOC7CmN80hbaGdjZJqsBR2UqXxJh5Coo=
    expiration: 86400
    refresh-expiration: 604800



# Token refresh endpoint URL
refresh:
  token:
    url: http://localhost:8081/api/auth/refresh

# CORS configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization,Refresh-Token
  max-age: 3600

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true

# Email Configuration
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: your-email@gmail.com
spring.mail.password: your-app-specific-password
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

# Frontend URL for password reset
app.frontend-url: http://localhost:3000

# Reset Password Token Configuration
app.reset-password.token.expiration: 900000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/  # ✅ Match Eureka Server port
