server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://localhost:3307/user
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 10
      max-size: 30
      max-idle-time: 30m
      validation-query: SELECT 1
  application:
    name: user-service
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:3307/user
    user: postgres
    password: postgres
    clean-disabled: true
    repair-on-migrate: true
  cloud:
    config:
      enabled: false

jwt:
  secret: ofBra2CqJO2JOC7CmN80hbaGdjZJqsBR2UqXxJh5Coo=
  expiration: 86400
  refresh-expiration: 604800

logging:
  level:
    root: INFO
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG
    dev.bengi.userservice: DEBUG
    org.springframework.security: DEBUG

cors:
  allowed-origins: 
    - http://localhost:3000
    - http://127.0.0.1:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: 
    - Authorization
    - Content-Type
    - X-Requested-With
    - Accept
    - Origin
    - Access-Control-Request-Method
    - Access-Control-Request-Headers
    - Refresh-Token
  exposed-headers: 
    - Authorization
    - Refresh-Token
  allow-credentials: true
  max-age: 3600

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8087/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    non-secure-port: ${server.port}
