server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3307/user
    username: postgres
    password: 6531503042
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: L8KwmXTT/ByT7e9ZiO0s5cGedE7cSfS5YKpC0Qn/qO8=
    expiration: 86400
    refresh-expiration: 86400

# Token refresh endpoint URL
refresh:
  token:
    url: http://localhost:8081/api/auth/refresh

# CORS configuration
cors:
  allowed-origins: http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: Authorization,Content-Type
  exposed-headers: Authorization,Refresh-Token
  max-age: 3600

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    syntaxHighlight:
      activated: true

# Enable or disable OpenAPI documentation
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

# Groups
springdoc:
  group-configs[0]:
    group: user-management
    paths-to-match: /api/manager/**
    packages-to-scan: dev.bengi.userservice.controller

# Email Configuration
spring.mail.host: smtp.gmail.com
spring.mail.port: 587
spring.mail.username: your-email@gmail.com
spring.mail.password: your-app-specific-password
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true

# Frontend URL for password reset
app.frontend-url: http://localhost:3000

# Reset Password Token Configuration
app.reset-password.token.expiration: 900000
