# Docker Compose for production
version: '3.8'

services:
  backend:
    build:
      context: ./Backend/main
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped
    depends_on:
      - backend

  employee-frontend:
    build:
      context: ./frontend/employee
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped
    depends_on:
      - backend

  postgres:
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d senior"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
