version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ata-postgres
    environment:
      POSTGRES_DB: senior
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"  # เปลี่ยนจาก 5432 เป็น 5433 เพื่อไม่ชนกับ PostgreSQL ท้องถิ่น
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Backend/main/src/main/resources/db/migration:/docker-entrypoint-initdb.d/
    networks:
      - ata-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d senior"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ata-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5051:80"  # เปลี่ยนจาก 5050 เป็น 5051
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - ata-network

  backend:
    build:
      context: ./Backend/main
      dockerfile: Dockerfile
    container_name: ata-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/senior
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/senior
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD=postgres123
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ata-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: ata-admin-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ata-network
    restart: unless-stopped

  employee-frontend:
    build:
      context: ./frontend/employee
      dockerfile: Dockerfile
    container_name: ata-employee-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ata-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ata-network:
    driver: bridge