version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: ata-postgres
    environment:
      POSTGRES_DB: senior
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d senior"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ata-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./Backend/main
      dockerfile: Dockerfile
    container_name: ata-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/senior
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD="postgres"
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/senior
      - SPRING_R2DBC_USERNAME=postgres
      - SPRING_R2DBC_PASSWORD="postgres"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./Backend/main:/app
    working_dir: /app

  admin-frontend:
    build:
      context: ./frontend/admin
      dockerfile: Dockerfile
    container_name: ata-admin-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
    working_dir: /app

  employee-frontend:
    build:
      context: ./frontend/employee
      dockerfile: Dockerfile
    container_name: ata-employee-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    depends_on:
      - backend
    volumes:
      - ./frontend/employee:/app
      - /app/node_modules
    working_dir: /app

volumes:
  postgres_data:
  pgadmin_data: