[[tls.certificates]]
  certFile = "/etc/traefik/certs/localhost.crt"
  keyFile = "/etc/traefik/certs/localhost.key"

[http.middlewares]
  [http.middlewares.cors.headers]
    accessControlAllowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
    accessControlAllowOriginList = ["*"]
    accessControlAllowHeaders = ["Authorization", "Content-Type", "Accept", "Origin", "X-Requested-With", "Refresh-Token"]
    accessControlExposeHeaders = ["Authorization", "Refresh-Token"]
    accessControlAllowCredentials = true
    accessControlMaxAge = 3600

  [http.middlewares.security-headers.headers]
    frameDeny = true
    browserXssFilter = true
    contentTypeNosniff = true
    stsIncludeSubdomains = true
    stsPreload = true
    stsSeconds = 31536000
    referrerPolicy = "same-origin"

  [http.middlewares.redirect-to-non-www.redirectregex]
    regex = "^https?://www\\.(.*)"
    replacement = "https://$1"
    permanent = true

[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    sniStrict = true
    cipherSuites = [
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    ] 