[global]
  checkNewVersion = false
  sendAnonymousUsage = false

[log]
  level = "INFO"
  format = "common"

[api]
  dashboard = true
  insecure = true

[providers]
  [providers.docker]
    exposedByDefault = false
    network = "hr-network"

  [providers.file]
    filename = "/etc/traefik/dynamic_conf.toml"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"

  [entryPoints.websecure]
    address = ":443"
    [entryPoints.websecure.http.tls]

# Include certificate files directly
[[tls.certificates]]
  certFile = "/etc/traefik/certs/localhost.crt"
  keyFile = "/etc/traefik/certs/localhost.key"

# Default TLS options
[tls.options.default]
  minVersion = "VersionTLS12"
  sniStrict = true
  cipherSuites = [
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
  ] 