server:
  port: 8084
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: feedback-service
  r2dbc:
    url: r2dbc:postgresql://localhost:3307/feedback
    username: postgres
    password: 6531503042
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  flyway:
    url: jdbc:postgresql://localhost:3307/feedback
    user: postgres
    password: 6531503042
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    clean-disabled: false
  webflux:
    base-path: /
  codec:
    max-in-memory-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

security:
  jwt:
    secret: L8KwmXTT/ByT7e9ZiO0s5cGedE7cSfS5YKpC0Qn/qO8=
    expiration: 86400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8087/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  user-service:
    url: http://localhost:8081

services:
  user-service:
    url: http://localhost:8081

logging:
  level:
    org.springframework.r2dbc: DEBUG
    dev.bengi.feedbackservice: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
