version: '3.8'

services:
  feedback-scoring-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feedback-scoring-service
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8085
      - API_RELOAD=False
      - API_WORKERS=2
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=feedback_analytics
      - FEEDBACK_SERVICE_URL=http://feedback-service:8084
      - USE_GPU=False
      - LOG_LEVEL=INFO
      - BATCH_SIZE=16
      - MAX_WORKERS=4
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./models:/app/models
    depends_on:
      - mongodb
    networks:
      - feedback-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=feedback_analytics
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - feedback-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/feedback_analytics --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  feedback-network:
    driver: bridge

volumes:
  mongodb-data: 