server:
  port: 8087

spring:
  application:
    name: discovery-service
  cloud:
    config:
      enabled: false  # Disable config server lookup

# Add actuator config for health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  instance:
    hostname: discovery-service  # Changed to match container name in docker-compose
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/