tunnel: mfu-app
credentials-file: /path/to/credentials.json

ingress:
  - hostname: api.yourdomain.com
    service: http://localhost:8080
  - hostname: admin.yourdomain.com
    service: http://localhost:3000
  - hostname: emp.yourdomain.com
    service: http://localhost:3001
  - service: http_status:404
