package dev.bengi.feedbackservice.domain.enums;

public enum QuestionCategory {
    WORK_ENVIRONMENT,
    WORK_LIFE_BALANCE,
    TEAM_COLLABORATION,
    PROJECT_MANAGEMENT,
    PROJECT_SATISFACTION,
    TECHNICAL_SKILLS,
    COMMUNICATION,
    LEADERSHIP,
    INNOVATION,
    PERSONAL_GROWTH,
    GENERAL
}