name: CI/CD Pipeline

on:
  push:
    branches: [deployment]
  pull_request:
    branches: [deployment]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          version: 1.2.2

      - name: Install root dependencies
        run: bun install

      - name: Start essential services (Redis)
        run: docker-compose up -d redis

      - name: Wait for Redis
        run: |
          echo "Waiting for Redis..."
          until docker exec ata-it-redis redis-cli ping | grep PONG; do sleep 1; done
          echo "✅ Redis is ready."

#   webflux:
#     runs-on: ubuntu-latest
#     needs: setup
#     steps:
#       - uses: actions/checkout@v4

#       - name: Install and build Webflux backend
#         run: |
#           cd backend/webflux
#           bun install
#           bun run build

  admin-frontend:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4

      - name: Build Admin Frontend
        run: |
          cd frontend/admin
          bun install
          bun build

  docker:
    runs-on: ubuntu-latest
    needs: [webflux, admin-frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Deploy all services
        run: docker-compose up -d --build

  deploy-staging:
    runs-on: self-hosted
    needs: docker
    steps:
      - name: Pull latest code
        run: git pull origin deployment

      - name: Docker Compose Up
        run: docker-compose up -d --build